CREATE TABLE delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_ref VARCHAR(50) NOT NULL,
    dest_address VARCHAR(300) NOT NULL,
    dest_lat NUMERIC(9,6),
    dest_lng NUMERIC(9,6),
    distance_km NUMERIC(10,2),
    zone VARCHAR(12) NOT NULL DEFAULT 'UNKNOWN',
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    geocoded_at TIMESTAMP WITH TIME ZONE,
    resolved_address VARCHAR(500),
    geocode_source VARCHAR(20) NOT NULL DEFAULT 'UNAVAILABLE',
    CONSTRAINT delivery_zone_check CHECK (zone IN ('LOCAL', 'REGIONAL', 'LONG_HAUL', 'UNKNOWN')),
    CONSTRAINT delivery_status_check CHECK (status IN ('PLANNED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED'))
);
CREATE INDEX delivery_zone_status_idx ON delivery(zone, status);

CREATE TABLE geocode_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR(300) NOT NULL UNIQUE,
    lat NUMERIC(9,6) NOT NULL,
    lng NUMERIC(9,6) NOT NULL,
    display_name VARCHAR(500),
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cache_lat_check CHECK (lat BETWEEN -90 AND 90),
    CONSTRAINT cache_lng_check CHECK (lng BETWEEN -180 AND 180)
);
